In [10]:
import numpy as np

In [11]:
# Sigmoid function
def sigmoid(x, deriv=False):  
    if(deriv==True):
        return (x*(1-x))
    
    return 1/(1+np.exp(-x))

In [12]:
#input data, 4x3 -> 3x4
x0 = np.array([[0,0,1],  
            [0,1,1],
            [1,0,1],
            [1,1,1]]).T

In [13]:
#output data, 1x4
y = np.array([[0,1,1,0]])

In [14]:
np.random.seed(1) # random seed between 0~1  

In [15]:
#synapses (weight)
# syn1 : 4x3 matrix of weights ( 4 nodes x (2 inputs + 1 bias) nodes in the hidden layer)
w1 = 2*np.random.random((4,3)) - 1 #(create matrix with random values between -1~1)
# syn2 : 1x4 matrix of weights. (1 output x 4 nodes ) - no bias term in the hidden layer.
w2 = 2*np.random.random((1,4)) - 1 #(create matrix with random values between -1~1)

In [16]:
print("syn1(w1) :", w1)
print("syn2(w2) :", w2)

syn1(w1) : [[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.30887855 -0.20646505]
 [ 0.07763347 -0.16161097  0.370439  ]]
syn2(w2) : [[-0.5910955   0.75623487 -0.94522481  0.34093502]]


In [17]:
#training step
# Python2 Note: In the follow command, you may improve 
# performance by replacing 'range' with 'xrange'. 
for j in range(60000):  
    
    # Calculate forward through the network.
    x1 = sigmoid(np.dot(w1,x0)) # size : 4x3 * 3x4 -> 4x4
    x2 = sigmoid(np.dot(w2,x1)) # size : 1x4 * 4x4 -> 4x4  
        
    error = (y-x2)
    # Back propagation of errors using the chain rule.
    # update w2 (no learning rate term, learning rate = 1)
    delta2 = (x2-y) * sigmoid(x2,deriv=True) # '*' operator for element wise product, 4x1   
    dc_dw2 = delta2.dot(x1.T) #1x4 * 4x4 => 1x4, same as weight 2
    w2 = w2 - dc_dw2 #1x4
   
    # update w1
    delta1 = w2.T.dot(delta2) * sigmoid(x1,deriv=True) #4x1 * 1x4 => 4x4 
    dc_dw1 = delta1.dot(x0.T) # 3x4 * 4x4 => 3x4
    w1 = w1 - dc_dw1 #3x4 
    
    if(j % 5000) == 0:   # Only print the error every 10000 steps, to save time and limit the amount of output. 
        print("Error: " + str(np.mean(np.abs(error))))
            
print("Output after training")
print(x2)

Error: 0.500620808426
Error: 0.0147264544862
Error: 0.00989516075228
Error: 0.00790705635172
Error: 0.00676094422549
Error: 0.00599458763722
Error: 0.00543683756555
Error: 0.00500792429942
Error: 0.00466505867747
Error: 0.00438298219174
Error: 0.00414570758813
Error: 0.00394256274682
Output after training
[[ 0.00401752  0.99559115  0.9969237   0.00356192]]


In [18]:
print(w1)
print(w2)

[[ 4.49894327  3.75410949 -6.43595796]
 [ 1.86775389 -2.81265121 -1.43409794]
 [-6.73016394 -7.21254635  3.06366556]
 [-3.91777283 -3.10928116  5.53211706]]
[[ -8.22581078   2.62827145 -13.22711053   6.65726387]]
